common: &common
  adapter: mysql2
  encoding: utf8
  username: root
  #password:
  #host: localhost
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *common
  database: hwt

development:
  <<: *common
  database: hwt

test:
  <<: *common
  database: hwt_test